<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE students SYSTEM "student.dtd">

<!--<!DOCTYPE students [-->
<!--        <!ELEMENT students (student*) >-->
<!--        <!ELEMENT student (name,age,sex)>-->
<!--        <!ELEMENT name (#PCDATA)>-->
<!--        <!ELEMENT age (#PCDATA)>-->
<!--        <!ELEMENT sex (#PCDATA)>-->
<!--        <!ATTLIST student number ID #REQUIRED>-->

<!--        -->
<!--        ]>-->


<students>
    <student number="Kobe_0001">
        <name>tom</name>
        <age>18</age>
        <sex>mail</sex>
    </student>

    <student number="Kobe_0002">
        <name>lisi</name>
        <age>24</age>
        <sex>femail</sex>
    </student>
</students>